### ISSUE TITLE
estimateMaxWorkspaceSize() is too small

### ISSUE THREAD

**Issue by leventov** [ning/compress#43]
```java
// len = 20
byte[] in = new byte[] {0, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0};
// 27, actually needs 28
int outSize = LZFEncoder.estimateMaxWorkspaceSize(in.length);
// IndexOutOfBoundsException
LZFEncoder.appendEncoded(in, 0, in.length, new byte[outSize], 0);
```

**Comment by cowtowncoder** [comment]
Thank you for reporting this. Sounds like a bug indeed, will fix.

**Comment by cowtowncoder** [comment]
Trying to fix this but goddang $#%_(($#^_)$#^$# TestNG is trying to prevent any work, failing in new spectacular ways. Almost tempted to convert test suite to junit...

Other than that, added test and will try to figure out what's wrong with the logics.

**Comment by cowtowncoder** [comment]
Ok so size estimation is slightly broken since rounding down of `1 << 5` and `1 << 6` misses one byte needed as length indicator for shortest; and probably can affect things up to 2 chunks. So I think I'll fix problem wrt shortest chunks with just adding `2`.

But I also noticed sort of reverse issue: estimates are too big for larger input, so I'll tackle that as well.

**Comment by cowtowncoder** [comment]
Looks like I don't have write access any more, no doubt due to Ning's reorg.
I'll have to see if I can find someone to give access, or if I'll have to fork this repo.
Sigh.

**Comment by myelin** [comment]
You should have access again now :)  Looks like someone went through and pruned out all the 'trusted external' accounts except for a couple of us.

**Comment by cowtowncoder** [comment]
@myelin Thanks! Yes, understandable. Just hadn't noticed before.

**Comment by cowtowncoder** [comment]
Pushing 1.0.4 release now with fixes.

**Comment by leventov** [comment]
@cowtowncoder thank you for this fantastically quick fix and release!

**Comment by cowtowncoder** [comment]
@leventov Thank you for reporting this!
